sudo: required
dist: trusty

language: python
python: 
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

addons:
    apt:
        packages:
        - gridengine-client
        - slurm-llnl

install:
    - wget https://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2
    - tar -xvjf parallel*
    - cd parallel*
    - ./configure
    - make
    - sudo make install
    - cd ..    
    - pip install -r requirements.txt -e .
    - pip install pycodestyle

script:
    - nosetests -v
    - pycodestyle qbatch/qbatch.py
