language: python
python: 
    - "2.6"
    - "2.7"

addons:
    apt:
        packages:
        - parallel 

install:
    - pip install .
    - pip install pep8

script:
    - nosetests -v
    - pep8 bin/qbatch test
