sudo: required
dist: trusty

language: python
python: 
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"

addons:
    apt:
        packages:
        - gridengine-client

install:
    - wget https://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2
    - tar -xvjf parallel*
    - cd parallel*
    - ./configure
    - make
    - sudo make install
    - cd ..    
    - pip install .
    - pip install pep8

script:
    - nosetests -v
    - pep8 bin/qbatch test
