#!/usr/bin/env python
#Stolen from https://stackoverflow.com/questions/26104116/qstat-and-long-job-names
#Adapted for Sun Grid Engine
import os
import sys
import xml.etree.ElementTree as ET
f = os.popen('qstat -xml')
try:
    tree = ET.parse(f)
except:
    sys.exit()
root = tree.getroot()
for queue in root:
    for job in queue:
        print job.find('JB_job_number').text, " ",
        print job.find('JB_name').text

