#!/usr/bin/env python
#Stolen from https://stackoverflow.com/questions/26104116/qstat-and-long-job-names
import subprocess
import sys
import xml.etree.ElementTree as ET
try:
    output = subprocess.check_output(['qstat', '-x'])
except subprocess.CalledProcessError as e:
    sys.exit(e)

try:
    tree = ET.fromstring(output)
except:
    sys.exit(1)

for job in tree:
  print job.find('Job_Id').text, " ",
  print job.find('Job_Name').text
